# Generated by Django 4.2.1 on 2023-07-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('document_number', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, default='email@email.com', max_length=100)),
                ('department', models.CharField(max_length=40)),
            ],
        ),
    ]
